<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-16T16:31:06 EDT" name="OAMTestSuite" finished-at="2022-05-16T16:31:21 EDT" duration-ms="15781">
    <groups>
    </groups>
    <test started-at="2022-05-16T16:31:06 EDT" name="OAMTests" finished-at="2022-05-16T16:31:21 EDT" duration-ms="15781">
      <class name="com.wac.cwp.testcases.FogrotPasswordTestCases">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wac.cwp.testcases.FogrotPasswordTestCases@6b09fb41]" started-at="2022-05-16T16:31:07 EDT" name="setUp" finished-at="2022-05-16T16:31:12 EDT" duration-ms="5326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validEmailExistingAndNonExisting_FP_10_11(java.util.HashMap,org.testng.ITestContext,org.testng.ITestResult)[pri:3, instance:com.wac.cwp.testcases.FogrotPasswordTestCases@6b09fb41]" started-at="2022-05-16T16:31:12 EDT" name="validEmailExistingAndNonExisting_FP_10_11" description="Failed login to customer web portal" data-provider="fp10_11" finished-at="2022-05-16T16:31:20 EDT" duration-ms="7630" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{isExecute=YES, Email=test1@worldaccepatnce.com, MainError=null, InstanceId=4.8592557E7, EmailExists=YES, AlternateEmail=null, TestCaseId=10.0, TestMethod=validEmailExistingAndNonExisting_FP_10_11, ConfirmPassword=Null, SuccessMessage=null, EmailSubject=World Acceptance Corporation account email verification code, RESEND=NO, ErrorMessage=Null, GmailPassword=V1h66Jydc#j*bVhp, Password=Null}]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@6f6621e3]]>
              </value>
            </param>
            <param index="2">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[AUTHENTICATE failed.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: AUTHENTICATE failed.
at org.testng.Assert.fail(Assert.java:99)
at com.wac.cwp.testcases.FogrotPasswordTestCases.validEmailExistingAndNonExisting_FP_10_11(FogrotPasswordTestCases.java:280)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validEmailExistingAndNonExisting_FP_10_11 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestContext,org.testng.ITestResult)[pri:0, instance:com.wac.cwp.testcases.FogrotPasswordTestCases@6b09fb41]" started-at="2022-05-16T16:31:20 EDT" name="tearDown" finished-at="2022-05-16T16:31:20 EDT" duration-ms="779" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6f6621e3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=validEmailExistingAndNonExisting_FP_10_11 status=FAILURE method=FogrotPasswordTestCases.validEmailExistingAndNonExisting_FP_10_11(java.util.HashMap,org.testng.ITestContext,org.testng.ITestResult)[pri:3, instance:com.wac.cwp.testcases.FogrotPasswordTestCases@6b09fb41] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.wac.cwp.testcases.FogrotPasswordTestCases -->
    </test> <!-- OAMTests -->
  </suite> <!-- OAMTestSuite -->
</testng-results>
